# Generated by Django 3.1.3 on 2020-12-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201203_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='Music.jpg', upload_to='media'),
        ),
    ]
